package com.sergioag13.srpringbootg13.model;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author desaextremo
 */
public class BaseDatosCursos {

    private Map<Integer, Curso> listaCursos;

    public BaseDatosCursos() {
        listaCursos = new HashMap<Integer,Curso>();

        listaCursos.put(1, new Curso(1, "Java para todos", "En este curso se abordan los fundamentos para entender y comprender como se programar con Java. En el primer módulo revisaremos la sintaxis del lenguaje y entenderemos los mecanismos básicos para la implementación de una clase, así como el uso de las API de las clases Java más utilizados. En el segundo módulo utilizaremos los conceptos del primer módulo para implementar clases y sus relaciones entendiendo los mecanismos propios de la orientación a objetos como son las relaciones entre clases, herencia, interfaces y polimorfismo. En el tercero y cuarto modulo se hace una introducción al desarrollo y utilización de estructuras de datos lineales y no lineales, así como la implementación de algoritmos de búsqueda y ordenamiento eficiente de datos. Luego del dominio de los elementos conceptuales y desarrollando ejercicios prácticos para adquirir habilidades y técnicas, puedes dominar todos los aspectos importantes de la plataforma de programación más popular del mundo. Con Java se pueden crear aplicaciones que funcionen en cualquier computador o servidor con sistemas operativos Windows, Linux o Mac y en dispositivos móviles.", "Operadores\r\nSintaxis Lenguage programación Java\r\nEstructuras de Control\r\nRelaciones entre Clases\r\nArreglos\r\nProgramación Orientada a Objetos\r\nFunciones"));
        listaCursos.put(2, new Curso(2, "Python Fundamentos de programación ", "El primer ciclo de formación de fundamentos de programación con Python presenta a los estudiantes estrategias para resolver problemas de la vida real aplicando lenguajes de programación estructurados como Python, mediante la aplicación de buenas prácticas de programación que ayudan a desarrollar el pensamiento lógico. Se tiene como propósito utilizar estrategias de pensamiento computacional como el paradigma “dividir y conquistar” para dividir problemas grandes en módulos o procedimientos, utilizando adecuadamente las variables simples, funciones, arreglos, iteraciones, recursión, el procesamiento básico de archivos y estructuras de datos sencillas. En este curso, los estudiantes resolverán diferentes retos de programación en Python adquiriendo competencias en el área de programación\r\n\r\n", "Manejo de estructuras de control de flujo\r\nManejo de funciones\r\nIntroducción a los algoritmos\r\nIntroducción a computación\r\nPersistencia de datos en Python"));
        listaCursos.put(3, new Curso(3, "Angular 12 - Desde cero hasta profesional", "Este curso es compatible con Angular 2 final, Angular 4, Angular 5, Angular 6, Angular 7, Angular 8, Angular 9, Angular 10, Angular 11 y Angular 12.\r\n\r\nAngular es el framework para JavaScript estándar para crear webs SPA. Es uno de los frameworks más populares para desarrollar aplicaciones modernas y escalables en el lado del cliente. Si quieres ser desarrollador front-end o full-stack, o incluso si ya te dedicas al desarrollo web, es casi obligatorio aprender Angular.\r\n\r\nAngular ha dado un salto de calidad con respecto a la versiones anteriores del framework, como AngularJS. Ahora utilizaremos TypeScript para definir nuestras clases, propiedades y métodos, el código es mucho más limpio y se ha mejorado el funcionamiento general del framework.\r\n\r\nAl finalizar el curso serás capaz de desarrollar tus propias aplicaciones web SPA (Single Page Apps) con Angular y modificar otras que ya estén programadas con este framework.", "Introducción\r\nInstalaciones y primeros pasos\r\nComponentes y plantillas\r\nTypeScript dentro de Angular\r\nDirectivas, binding y eventos\r\nRouting y navegación\r\nServicios\r\nPipes"));
        listaCursos.put(4, new Curso(4, "Curso Básico de JavaScript", "Conoce los conceptos clave del lenguaje de programación que se está comiendo al mundo. Aprende qué es una variable, una función, un objeto y dónde se guardan esos valores. Descubre qué es Scope y cómo se utilizan los loops. Obtén las herramientas para saber cómo tomar decisiones y validar acciones. En este curso, darás el primer paso para empezar tu carrera como desarrollador.\r\n\r\nConocer los conceptos básicos de JS\r\nDescubrir la historia de JavaScript\r\nAprender cómo tomar decisiones y validarlas\r\nTrabajar con objetos", "¿Qué es JavaScript?\r\n¿Por qué JavaScript?\r\nElementos de un Lenguaje de Programación: Variables, Funciones y Sintaxis\r\n\r\n"));
        listaCursos.put(5, new Curso(5, "Curso de Webpack", "Webpack es un module bundler o empaquetador de módulos para JavaScript. Domina el uso de loaders y plugins para integrar tus herramientas favoritas a un entorno de desarrollo o producción. Optimiza tus proyectos con compresión y minificación de archivos. Configura Webpack con HTML, CSS, JavaScript, React.js, imágenes y fuentes para convertirte en frontend profesional con tu profesor Oscar Barajas.\r\n\r\nDescubrir cuándo necesitas un module bundler\r\nConfigurar un entorno de desarrollo profesional con Webpack\r\nPreparar un bundle para enviar a producción con Webpack\r\nCompilar tu proyecto con webpack", "Introducción a Webpack\r\n"));
        listaCursos.put(6, new Curso(6, "Curso Profesional de Git y GitHub", "Deja de versionar tus proyectos usando tu propio sistema de control de versiones. Mejor usa Git, el sistema de control de versiones por excelencia que utiliza la industria tecnológica. Aprende a trabajar con git, conceptos básicos, clonar un repositorio y gestionar tus proyectos alojándolos en tu repositorio local y en GitHub.\r\n\r\nLlevar un Control de Versiones en tus Proyectos con Git\r\nTrabajar en Equipos de Forma Colaborativa\r\nUtilizar Dominios Personalizados con GitHub Pages\r\nInstalar Git en tu sistema operativo\r\n", "pendiente"));
        listaCursos.put(7, new Curso(7, "Fundamentos de Ingeniería de Software", "Comienza tu proyecto aprendiendo las bases de la ingeniería de software. En este curso podrás entender cómo funcionan las bases de la electrónica, los diferentes sistemas operativos y las redes que te permiten usar Internet.\r\n\r\nConocer la arquitectura de una computadora\r\nEntender cómo funciona Internet\r\nIntroducirte al mundo de las redes y el cloud\r\nComprender la industria del software", "pendiente"));
        listaCursos.put(8, new Curso(8, "Curso Práctico de HTML y CSS", "Ahora que ya tienes todos los conocimientos de HTML y CSS, estás listo para este curso práctico en el cual tendrás un reto: clonar la página de Google. Reforzarás conceptos como posicionamiento, modelo de cajas, tipos de Display, selectores como clases, IDS, Flexbox y Grid.\r\n\r\nCrear el Header de una página\r\nEstructurar el contenido principal de una página\r\nConstruir el Footer de una página", "pendiente"));
        listaCursos.put(9, new Curso(9, "Curso de Frontend Developer", "Domina las bases de HTML y CSS. Conoce la anatomía de un documento HTML, sus elementos y las propiedades de CSS. Maqueta las pantallas principales de tu página web con responsive design. ¡Conviertete en Frontend Developer con Platzi!\r\n\r\nDescubre las ventajas del responsive design y las arquitecturas CSS\r\nComprende cómo se transforma el código HTML y CSS en página web\r\nConoce las etiquetas más importantes de HTML\r\nUsa correctamente las propiedades y selectores de CSS\r\n", "pendiente"));
        listaCursos.put(10, new Curso(10, "Curso de CSS Grid Básico", "Aprende a crear layouts dinámicos con CSS Grid! Aplica diseños complejos en tu sitio web con pocas líneas de código CSS. Construye grillas para distribuir tus contenedores y elementos HTML ágilmente con tu profesora Estefany Salas.\r\n\r\nConstruye layouts complejos de manera sencilla y responsiva\r\nPosiciona ítems y contenedores\r\nControla ítems a través de filas y columnas\r\nDistingue las diferentes propiedades de CSS Grid", "pendiente"));
        listaCursos.put(11, new Curso(11, "Curso de Python Intermedio", "Fortalece tus habilidades para profesionalizarte con Python, uno de los lenguajes más utilizados en el mundo en desarrollo backend, ciencia de datos e inteligencia artificial. Aprende conceptos y practica con retos que elevarán tu nivel al programar.\r\n\r\nUtiliza list y dictionary comprehensions, y high order functions.\r\nPreparar un entorno virtual con pip.\r\nManeja archivos de texto con el context manager.\r\nAprende qué significan los errores y cómo manejarlos.", "pendiente"));
        listaCursos.put(12, new Curso(12, "Curso de Introducción a la Producción de Videojuegos", "¿Te has preguntado cuál es el trabajo de un productor de videojuegos? Conoce quiénes integran al equipo que crea videojuegos y cuál es el rol de cada uno. Podrás aprender sobre las distintas etapas por las que pasa el desarrollo de un videojuego, desde pre producción hasta contenido post lanzamiento y todo lo que implica. Lograrás entender la diferencia entre un pitch de videojuegos y startups cuando buscas financiamiento para tu proyecto.\r\n\r\nEscribir un kit de prensa que le permita una difusión exitosa a tu videojuego.\r\nPlanificar presupuesto tomando en cuenta personal, equipo y licencias.\r\nDesarrollar las bases de un vertical slice.\r\nDiseñar un slide deck para videojuegos.", "pendiente"));
        listaCursos.put(13, new Curso(13, "Curso de Introducción a la Terminal y Línea de Comandos", "La terminal y línea de comandos es una herramienta esencial que todo desarrollador de software, sin importar su área de especialización, pues se encuentra presente de forma universal. En este curso aprenderás a aprovechar el potencial de los sistemas operativos basados en UNIX siendo capaz de dominar los comandos básicos de la terminal, realizar búsquedas que agilicen tu trabajo y administrar permisos en tu equipo.\r\n\r\nCrearás tus propios alias y variables de entorno para ahorrar tiempo.\r\nPodrás manipular archivos y directorios desde la terminal.\r\nPersonalizarás tu terminal de acuerdo a las necesidades de tu proyecto.\r\nAprenderás comandos básicos para usar la terminal.", "pendiente"));
        listaCursos.put(14, new Curso(14, "Go para Dummies", "Go es un lenguaje creado por Google en 2009 y que ha ganado mucha fuerza en el desarrollo actual. De hecho, empresas como Dropbox, Docker, Facebook, Netflix, Uber oTwitter (entre otras) confian en Go para sus desarrollos (fuente). Con Go puedes programar tu aplicación una sola vez y luego compilarla para cualquier sistema operativo (incluso móviles). Además tiene una curva de aprendizaje sencilla pero a la vez el poder y robustez de lenguajes como C, siendo su especialidad los sistemas que requieran alto rendimiento.", "1.- Curso Go - Introducción\n2.- Curso Go - Instalación y Hola Mundo\n3.- Curso Go - Variables\n4.- Curso Go - Conversión de tipos\n5.- Curso Go - Leer e imprimir datos\n6.- Curso Go - Condiciones\n7.- Curso Go - Ciclos\n8.- Curso Go - Arreglos\n9.- Curso Go - Slices\n10.- Curso Go - Make y Append\n11.- Curso Go - Copy\n12.- Curso Go - Punteros\n13.- Curso Go - Structs\n14.- Curso Go - Métodos\n15.- Curso Go - Campos anónimos\n16.- Curso Go - Interfaces\n17.- Curso Go - Goroutines\n18.- Curso Go - Channels\n19.- Curso Go - Leer archivos v1\n20.- Curso Go - Leer archivo v2\n21.- Curso Go - Defer\n22.- Curso Go - Panic y Recover\n23.- Curso Go - Hola Mundo web\n24.- Curso Go - Servir archivos estáticos\n25.- Curso Go - Enviar JSON\n26.- Curso Go - Creación de Paquetes"));
    }

    public Map getListaCursos() {
        return listaCursos;
    }   
    
}
